Responsive design files
Yilikal250/Personal-Portfolio pull request #3
Opened 2022-03-25 17:57 UTC by Yilikal250

This is a desktop-version  web the first mobile version was done and because we want the web to be responsive we have added this version.

2022-03-25 20:09 UTC, akucintavalent requested changes
Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost there](https://c.tenor.com/wsMZNmu5xWQAAAAC/almost-there-almost.gif)

### To highlight :tada: :champagne: 
- GitHub flow is followed :+1:


## Required Changes ♻️

- [ ] Kindly update your README to contain detailed instructions on how to open the page locally.

- [ ] Please make sure your page is not scrollable horizontally in windows of any size and kindly get rid of this white space:

<img width="999" alt="Zrzut ekranu 2022-03-25 o 20 14 55" src="https://user-images.githubusercontent.com/87897753/160186984-cde66fe6-ae20-4018-9e54-be8514e3b17f.png">

- [ ] Please take care of responsiveness of the page:

https://user-images.githubusercontent.com/87897753/160188533-515f472e-db6f-4bd5-beda-09299d517239.mp4

- [ ] When I change the size of the window the background image should not hide.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/87897753/160189070-c01db9fd-410e-4f2a-b811-2a9866511518.png">

- [ ] Kindly take a look at the following picture and fix the highlighted problems. Your page should be responsive and that means it should look well on all screen/window sizes. For the mobile version you should: center the titles, the texts the cards. Background images of the sections should be aligned to the right side. Kindly fix the distances because some of them ar too small and some are too big.

![image](https://user-images.githubusercontent.com/87897753/160190482-751edd9a-c47f-4b3b-aed2-653fc627542e.png)

- [ ] When adding the desktop version of the page you should not break the mobile version.  Kindly fix all the problems in the mobile version. 

- [ ] Your project card buttons should not be separate from the cards:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/87897753/160191867-a91efa34-bbf3-42e0-b1ec-ac41d5c959c1.png">

- [ ] Kindly follow the Figma template as much as possible taking care of the responsiveness of your project. I could not possibly point out every problem with this project. I have been reviewing it for two hours. And it should take 30 minutes.

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +          <a>contact</a>
Please change the font to `Inter` for it to be the same as in the Figma template. Your current font for these elements is `Times`

2022-03-25 20:09 UTC, akucintavalent commented on index.html
>        <a id="name">John Doe</a>
Please change the font from Roboto to Inter for it to be a replica of the Figma template.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
>        <h2>I'm a Software Developer</h2>
Kindly change the font to `Inter`.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +        don’t hestiate to contact me.
Kindly change the font to `Inter`.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +              <button class="button" type="button">Ruby</button>
Kindly change the font of these elements to `Inter` instead of `Arial`.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +            </li>
Kindly change the font of these and all similar buttons to `Inter`.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
>          <h2><span id="diamond"></span> Language</h2>
Kindly change the font of these titles to `Inter`

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +        </p>
Please change the font to `Inter`.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +      </div>
Kindy change the font of the form placeholders to `Roboto`

2022-03-25 20:09 UTC, akucintavalent commented on style.css
> +  }
Kindly change the background color of the section to `#1C1A19`

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +          <a id="postpic"><img src="/post.png" alt=""></a>
This picture is not shown on the page

Your project:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/87897753/160181458-a4c92642-9e8e-4983-8770-9e5a426a3390.png">


Figma design:
<img width="177" alt="image" src="https://user-images.githubusercontent.com/87897753/160181375-767de9ed-70c2-422f-ba52-137822d5dba8.png">

In order to fix that, you should change `src="/post.png"` to `src="./post.png"`

2022-03-25 20:09 UTC, akucintavalent commented on index.html
>      <div class="toolbar">
Please fix the color of your navbar it should be `background: #3E3C3C;`

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +        <button type="button" class="postb">See Project</button>
Your orange buttons have borders that they should not have.

Your project:
<img width="114" alt="image" src="https://user-images.githubusercontent.com/87897753/160182211-390ec4da-9a1c-4077-a926-b676fa3ff5a1.png">

Figma design:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/87897753/160182279-e409ea32-ef3f-49c3-8275-c5ae4ab6ab65.png">

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +        <button type="button" class="postb">See Project</button>
Your button looks like that when hovered:

<img width="115" alt="image" src="https://user-images.githubusercontent.com/87897753/160182580-b82ee887-a6b0-4522-91f0-24c4a32944fb.png">

But should look like that when hovered
<img width="153" alt="image" src="https://user-images.githubusercontent.com/87897753/160182653-9c1a1717-8f9f-4720-8666-12177bf318a6.png">

It doesn't look as expected when pressed also. Take a look at Figma design:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/87897753/160182761-7f9ed6d1-41cd-429e-bd00-939c286d36e3.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/87897753/160182949-971cfbf1-75ec-4dcb-b805-863fe7a57ff7.png">

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +      <button class="postb1" type="button">Get My Resume</button>
This button's look doesn't change when it is hovered over or when it is pressed. Kindly follow the Figma design

<img width="515" alt="image" src="https://user-images.githubusercontent.com/87897753/160183150-83a0d736-4880-4af3-9aee-f697e330bf26.png">

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +            <button class="footer-button" type="submit">Get in touch</button>
This button also doesn't look as expected in all three states.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +          <textarea  class="full" name="textarea" id="textarea" placeholder="Enter text here" maxlength="500" required></textarea>
Input fields should have color `background: #FBF8F7;` when focus is on them.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
>          contact me.
Kindly fix the text size to be like on the Figma template.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +        </p>
Kindly fix the font size to be like on the template.

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +      </div>
Your form takes too much space on the page. Its left edge should not be more than `60vw` far from the right edge of the page :
<img width="984" alt="image" src="https://user-images.githubusercontent.com/87897753/160184749-f6d183d6-75f5-4d94-9d64-75d3ccc5d4f3.png">

Figma template:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/87897753/160184821-4aff777a-57a9-431c-910f-c025b9f7b6cf.png">

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +        </nav>
Kindly fix the distances between elements on your project cards:

Your design:
<img width="275" alt="Zrzut ekranu 2022-03-25 o 20 08 44" src="https://user-images.githubusercontent.com/87897753/160186148-5e912822-cd33-4bdc-8de2-9a87213a072e.png">

Figma template:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/87897753/160186226-8f7db9bb-40d0-4986-a030-f3e3004214ab.png">

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +      <hr  id="linenew">
Please fix the location of this line:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/87897753/160186616-76b73853-5884-40bf-a81c-cbd3e1c11763.png">

Figma template:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/87897753/160186547-3aea8b57-044a-423c-b205-15abc976354b.png">

2022-03-25 20:09 UTC, akucintavalent commented on index.html
> +      </nav>
Please don't use `nav`s for your cards, because the `<nav>` tag is used for declaring the navigational section in HTML documents.

2022-03-25 20:09 UTC, akucintavalent commented on style.css
> +@media screen and (min-width: 760px) {
This mediaquery's min-width argument should have a value of no less than 768px

2022-03-25 20:09 UTC, akucintavalent commented on style.css
> +  } */
Please remove commented code from your document because your code looks unclean.

2022-03-26 23:21 UTC, bimbolabuari requested changes
Hi @Yilikal250, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- Kindly make the changes requested by the previous code reviewer

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 15:13 UTC, closed without merging